Draft: Combine multiple `ElectronicFrictionProvider`s (or `Model`s) into a single model.
NQCD/NQCModels.jl pull request #39
Opened 2024-07-22 08:59 UTC by Alexsp32

# Phonon thermostatting in NQCD

Implements MDEF + 2TM with Phonon coupling (https://github.com/NQCD/NQCDynamics.jl/issues/73) by introducing `Subsystem`s, which apply a `Model` exclusively to certain atoms in a `Simulation`. These can be combined arbitrarily for `Model` types implementing `potential`, `derivative` or `friction`. 

![image](https://github.com/user-attachments/assets/6361f72f-a10f-483d-af8d-dd4dfc05b083)

The changes to `Simulation`s in https://github.com/NQCD/NQCDynamics.jl/pull/349 allow the use of different temperatures (either a constant value or function) for each atom by using `Thermostat`s, which behave like a `Subsystem`, applying a temperature to parts of a `Simulation`. 

![CompositeModel and Thermostat struct](https://github.com/user-attachments/assets/2fdfe0f0-687c-4e0e-a70c-ce6b1e1ebd24)

---
## ToDo

- [ ] Update documentation for new additions. 
- [ ] Demonstrate usage with harmonic oscillator model used to validate implementation. 
- [ ] Turn validation examples into unit tests.

2025-02-18 19:27 UTC, reinimaurer1 commented on src/subsystems.jl
> +**When combined in a CompositeModel**, `potential()`, `derivative!()` and `friction!()` will be sourced from the respective Subsystems.
this will also be really useful when using an MLIP and a long-range correction to that MLIP

2025-02-18 19:30 UTC, reinimaurer1 commented on src/subsystems.jl
> +**When combined in a CompositeModel**, `potential()`, `derivative!()` and `friction!()` will be sourced from the respective Subsystems.
does that mean, in terms of design philosophy, we would not want adiabatic models to do anything other than potential and derivative and that, if somebody wants to implement additional properties, those need to be implemented as separate NQCModel objects with this other property? 

Let's consider the case of an adiabatic model that provides potential and derivative for multiple electronic states, plus the corresponding nonadiabatic couplings (maybe through an ML model). and now I want to combine this with a friction provide for electronic friction or a long-range correction

2025-02-18 19:41 UTC, reinimaurer1 requested changes
all good. would it be possible to come up with a simple unit test for Subsystem and CompositeModel?

2025-02-19 10:38 UTC, Alexsp32 commented on src/subsystems.jl
> +**When combined in a CompositeModel**, `potential()`, `derivative!()` and `friction!()` will be sourced from the respective Subsystems.
Default behaviour for multiple subsystems assigned to same atoms: Additive

2025-02-19 16:54 UTC, reinimaurer1 approved these changes
thanks for adding the test

2025-02-19 17:01 UTC, merged